### ISSUE TITLE
Ensure conformance to upcoming Transak API changes (by August 31, 2022)

### ISSUE THREAD

**Issue by markmhx** [hirosystems/stacks-wallet-web#2431]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/28991/168846964-ef22913a-8c78-466b-92a3-795b15fd7bdd.png">

**Comment by fbwoolf** [comment]
@markmhx can you post the link from that email(?) just to make sure I am referencing the `new version` of their docs?

**Comment by fbwoolf** [comment]
What I am referencing still shows the apiKey being passed as a query param: https://transak.gitbook.io/transak-docs/coverage-and-capabilities/integration-options/browser-redirect-integration

EDIT: I am thinking maybe the changes don't impact us but only those using the Transak API?

**Comment by markmhendrickson** [comment]
Here's the link: 

https://docs.transak.com/docs/transak-docs/23934889ad961-transak-api

I've forwarded the emails as well in case helpful.

**Comment by fbwoolf** [comment]
@markmhx I don't believe this impacts us, we are not making requests to the api. We are just using the `Browser redirect integration` here: https://transak.gitbook.io/transak-docs/coverage-and-capabilities/integration-options/browser-redirect-integration
